In [19]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.metrics import categorical_accuracy

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn import datasets 


# fix random seed for reproducibility
seed = 7
np.random.seed(seed)

iris = datasets.load_iris()

In [20]:
X, y = iris.data, iris.target

In [21]:
X.shape

(150, 4)

In [22]:
y.shape

(150,)

In [23]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [24]:
from keras.utils import np_utils
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(y)
dummy_y[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [25]:
#dummy_y

In [26]:
# create model
model = Sequential()
model.add(Dense(3, input_dim=4, activation='softmax'))
# Compile model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, dummy_y, test_size=0.33, random_state=42)

In [28]:
len(y_train), len(y_test)

(100, 50)

In [33]:
# x_train and y_train are Numpy arrays --just like in the Scikit-Learn API.
model.fit(X_train, y_train, epochs=200, batch_size=16)

Epoch 1/200
100/100 [==============================] - 0s 95us/step - loss: 0.3549 - acc: 0.9400
Epoch 2/200
100/100 [==============================] - 0s 113us/step - loss: 0.3543 - acc: 0.9400
Epoch 3/200
100/100 [==============================] - 0s 91us/step - loss: 0.3533 - acc: 0.9500
Epoch 4/200
100/100 [==============================] - 0s 102us/step - loss: 0.3530 - acc: 0.9600
Epoch 5/200
100/100 [==============================] - 0s 107us/step - loss: 0.3523 - acc: 0.9500
Epoch 6/200
100/100 [==============================] - 0s 90us/step - loss: 0.3523 - acc: 0.9500
Epoch 7/200
100/100 [==============================] - 0s 78us/step - loss: 0.3517 - acc: 0.9600
Epoch 8/200
100/100 [==============================] - 0s 90us/step - loss: 0.3515 - acc: 0.9700
Epoch 9/200
100/100 [==============================] - 0s 84us/step - loss: 0.3512 - acc: 0.9700
Epoch 10/200
100/100 [==============================] - 0s 83us/step - loss: 0.3506 - acc: 0.9700
Epoch 11/200
100/100 [====

100/100 [==============================] - 0s 87us/step - loss: 0.3230 - acc: 0.9600
Epoch 85/200
100/100 [==============================] - 0s 90us/step - loss: 0.3227 - acc: 0.9600
Epoch 86/200
100/100 [==============================] - 0s 78us/step - loss: 0.3228 - acc: 0.9500
Epoch 87/200
100/100 [==============================] - 0s 84us/step - loss: 0.3220 - acc: 0.9600
Epoch 88/200
100/100 [==============================] - 0s 81us/step - loss: 0.3215 - acc: 0.9600
Epoch 89/200
100/100 [==============================] - 0s 80us/step - loss: 0.3212 - acc: 0.9500
Epoch 90/200
100/100 [==============================] - 0s 80us/step - loss: 0.3208 - acc: 0.9500
Epoch 91/200
100/100 [==============================] - 0s 80us/step - loss: 0.3205 - acc: 0.9500
Epoch 92/200
100/100 [==============================] - 0s 86us/step - loss: 0.3205 - acc: 0.9500
Epoch 93/200
100/100 [==============================] - 0s 88us/step - loss: 0.3200 - acc: 0.9500
Epoch 94/200
100/100 [===========

100/100 [==============================] - 0s 78us/step - loss: 0.2959 - acc: 0.9700
Epoch 168/200
100/100 [==============================] - 0s 88us/step - loss: 0.2959 - acc: 0.9600
Epoch 169/200
100/100 [==============================] - 0s 103us/step - loss: 0.2955 - acc: 0.9600
Epoch 170/200
100/100 [==============================] - 0s 86us/step - loss: 0.2951 - acc: 0.9600
Epoch 171/200
100/100 [==============================] - 0s 88us/step - loss: 0.2948 - acc: 0.9600
Epoch 172/200
100/100 [==============================] - 0s 85us/step - loss: 0.2944 - acc: 0.9600
Epoch 173/200
100/100 [==============================] - 0s 84us/step - loss: 0.2939 - acc: 0.9700
Epoch 174/200
100/100 [==============================] - 0s 88us/step - loss: 0.2940 - acc: 0.9700
Epoch 175/200
100/100 [==============================] - 0s 82us/step - loss: 0.2949 - acc: 0.9700
Epoch 176/200
100/100 [==============================] - 0s 83us/step - loss: 0.2948 - acc: 0.9700
Epoch 177/200
100/100 [

In [34]:
loss, accuracy = model.evaluate(X_test, y_test)
loss, accuracy

50/50 [==============================] - 0s 738us/step


(0.24586503207683563, 0.9799999904632568)

In [35]:
predictions = model.predict(X_test)
predictions

array([[6.9977962e-03, 6.7372447e-01, 3.1927776e-01],
       [9.8180860e-01, 1.8041894e-02, 1.4945841e-04],
       [4.1576104e-06, 1.2410629e-01, 8.7588954e-01],
       [5.4593091e-03, 5.8077925e-01, 4.1376144e-01],
       [5.9862984e-03, 6.6754359e-01, 3.2647008e-01],
       [9.7352409e-01, 2.6133599e-02, 3.4228701e-04],
       [4.7319602e-02, 7.1212626e-01, 2.4055411e-01],
       [3.9516078e-04, 2.9102987e-01, 7.0857489e-01],
       [2.5777952e-03, 5.0701749e-01, 4.9040470e-01],
       [2.8614106e-02, 7.2109169e-01, 2.5029424e-01],
       [7.6894625e-04, 3.7433422e-01, 6.2489682e-01],
       [9.7277111e-01, 2.6887402e-02, 3.4151983e-04],
       [9.8954880e-01, 1.0377887e-02, 7.3326082e-05],
       [9.7177011e-01, 2.7892666e-02, 3.3722230e-04],
       [9.8253572e-01, 1.7287953e-02, 1.7624942e-04],
       [5.7352404e-03, 6.0311544e-01, 3.9114940e-01],
       [5.1818522e-05, 1.8665178e-01, 8.1329638e-01],
       [2.4454193e-02, 7.1427441e-01, 2.6127139e-01],
       [6.2350933e-03, 6.119

In [41]:
np.round(predictions * 100)/100

array([[0.01, 0.67, 0.32],
       [0.98, 0.02, 0.  ],
       [0.  , 0.12, 0.88],
       [0.01, 0.58, 0.41],
       [0.01, 0.67, 0.33],
       [0.97, 0.03, 0.  ],
       [0.05, 0.71, 0.24],
       [0.  , 0.29, 0.71],
       [0.  , 0.51, 0.49],
       [0.03, 0.72, 0.25],
       [0.  , 0.37, 0.62],
       [0.97, 0.03, 0.  ],
       [0.99, 0.01, 0.  ],
       [0.97, 0.03, 0.  ],
       [0.98, 0.02, 0.  ],
       [0.01, 0.6 , 0.39],
       [0.  , 0.19, 0.81],
       [0.02, 0.71, 0.26],
       [0.01, 0.61, 0.38],
       [0.  , 0.18, 0.82],
       [0.96, 0.04, 0.  ],
       [0.  , 0.41, 0.59],
       [0.96, 0.04, 0.  ],
       [0.  , 0.21, 0.79],
       [0.  , 0.44, 0.56],
       [0.  , 0.24, 0.76],
       [0.  , 0.28, 0.72],
       [0.  , 0.19, 0.81],
       [0.96, 0.04, 0.  ],
       [0.96, 0.04, 0.  ],
       [0.99, 0.01, 0.  ],
       [0.99, 0.01, 0.  ],
       [0.02, 0.74, 0.24],
       [0.97, 0.03, 0.  ],
       [0.97, 0.03, 0.  ],
       [0.  , 0.31, 0.69],
       [0.01, 0.67, 0.32],
 

In [42]:
predictions.astype('float32')

array([[6.9977962e-03, 6.7372447e-01, 3.1927776e-01],
       [9.8180860e-01, 1.8041894e-02, 1.4945841e-04],
       [4.1576104e-06, 1.2410629e-01, 8.7588954e-01],
       [5.4593091e-03, 5.8077925e-01, 4.1376144e-01],
       [5.9862984e-03, 6.6754359e-01, 3.2647008e-01],
       [9.7352409e-01, 2.6133599e-02, 3.4228701e-04],
       [4.7319602e-02, 7.1212626e-01, 2.4055411e-01],
       [3.9516078e-04, 2.9102987e-01, 7.0857489e-01],
       [2.5777952e-03, 5.0701749e-01, 4.9040470e-01],
       [2.8614106e-02, 7.2109169e-01, 2.5029424e-01],
       [7.6894625e-04, 3.7433422e-01, 6.2489682e-01],
       [9.7277111e-01, 2.6887402e-02, 3.4151983e-04],
       [9.8954880e-01, 1.0377887e-02, 7.3326082e-05],
       [9.7177011e-01, 2.7892666e-02, 3.3722230e-04],
       [9.8253572e-01, 1.7287953e-02, 1.7624942e-04],
       [5.7352404e-03, 6.0311544e-01, 3.9114940e-01],
       [5.1818522e-05, 1.8665178e-01, 8.1329638e-01],
       [2.4454193e-02, 7.1427441e-01, 2.6127139e-01],
       [6.2350933e-03, 6.119

In [36]:
pred = np.argmax(predictions, axis = 1)
pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2])

In [37]:
y_test

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0

In [38]:
y_true =np.argmax(y_test, axis = 1)
y_true

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [39]:
np.mean(pred == y_true)

0.98

# 1 more layer

In [46]:
# create model
model = Sequential()
model.add(Dense(6, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))
# Compile model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [47]:
# x_train and y_train are Numpy arrays --just like in the Scikit-Learn API.
model.fit(X_train, y_train, epochs=500)

Epoch 1/500
100/100 [==============================] - 0s 2ms/step - loss: 2.6300 - acc: 0.3700
Epoch 2/500
100/100 [==============================] - 0s 66us/step - loss: 2.5076 - acc: 0.4900
Epoch 3/500
100/100 [==============================] - 0s 68us/step - loss: 2.3867 - acc: 0.6100
Epoch 4/500
100/100 [==============================] - 0s 59us/step - loss: 2.2680 - acc: 0.6300
Epoch 5/500
100/100 [==============================] - 0s 59us/step - loss: 2.1622 - acc: 0.6300
Epoch 6/500
100/100 [==============================] - 0s 63us/step - loss: 2.0522 - acc: 0.6500
Epoch 7/500
100/100 [==============================] - 0s 67us/step - loss: 1.9538 - acc: 0.6500
Epoch 8/500
100/100 [==============================] - 0s 64us/step - loss: 1.8559 - acc: 0.6500
Epoch 9/500
100/100 [==============================] - 0s 55us/step - loss: 1.7561 - acc: 0.6500
Epoch 10/500
100/100 [==============================] - 0s 63us/step - loss: 1.6657 - acc: 0.6500
Epoch 11/500
100/100 [========

100/100 [==============================] - 0s 67us/step - loss: 0.5538 - acc: 0.9100
Epoch 85/500
100/100 [==============================] - 0s 65us/step - loss: 0.5510 - acc: 0.9100
Epoch 86/500
100/100 [==============================] - 0s 60us/step - loss: 0.5490 - acc: 0.8900
Epoch 87/500
100/100 [==============================] - 0s 59us/step - loss: 0.5460 - acc: 0.8900
Epoch 88/500
100/100 [==============================] - 0s 67us/step - loss: 0.5423 - acc: 0.9000
Epoch 89/500
100/100 [==============================] - 0s 62us/step - loss: 0.5386 - acc: 0.9000
Epoch 90/500
100/100 [==============================] - 0s 54us/step - loss: 0.5351 - acc: 0.9100
Epoch 91/500
100/100 [==============================] - 0s 60us/step - loss: 0.5318 - acc: 0.9200
Epoch 92/500
100/100 [==============================] - 0s 61us/step - loss: 0.5283 - acc: 0.9200
Epoch 93/500
100/100 [==============================] - 0s 61us/step - loss: 0.5251 - acc: 0.9200
Epoch 94/500
100/100 [===========

100/100 [==============================] - 0s 58us/step - loss: 0.3710 - acc: 0.9400
Epoch 168/500
100/100 [==============================] - 0s 59us/step - loss: 0.3692 - acc: 0.9400
Epoch 169/500
100/100 [==============================] - 0s 63us/step - loss: 0.3673 - acc: 0.9400
Epoch 170/500
100/100 [==============================] - 0s 60us/step - loss: 0.3661 - acc: 0.9400
Epoch 171/500
100/100 [==============================] - 0s 54us/step - loss: 0.3647 - acc: 0.9400
Epoch 172/500
100/100 [==============================] - 0s 51us/step - loss: 0.3632 - acc: 0.9400
Epoch 173/500
100/100 [==============================] - 0s 61us/step - loss: 0.3618 - acc: 0.9500
Epoch 174/500
100/100 [==============================] - 0s 59us/step - loss: 0.3606 - acc: 0.9500
Epoch 175/500
100/100 [==============================] - 0s 55us/step - loss: 0.3593 - acc: 0.9500
Epoch 176/500
100/100 [==============================] - 0s 68us/step - loss: 0.3579 - acc: 0.9500
Epoch 177/500
100/100 [=

100/100 [==============================] - 0s 59us/step - loss: 0.2873 - acc: 0.9300
Epoch 250/500
100/100 [==============================] - 0s 64us/step - loss: 0.2865 - acc: 0.9300
Epoch 251/500
100/100 [==============================] - 0s 61us/step - loss: 0.2846 - acc: 0.9400
Epoch 252/500
100/100 [==============================] - 0s 67us/step - loss: 0.2810 - acc: 0.9500
Epoch 253/500
100/100 [==============================] - 0s 64us/step - loss: 0.2789 - acc: 0.9500
Epoch 254/500
100/100 [==============================] - 0s 78us/step - loss: 0.2771 - acc: 0.9500
Epoch 255/500
100/100 [==============================] - 0s 63us/step - loss: 0.2756 - acc: 0.9700
Epoch 256/500
100/100 [==============================] - 0s 67us/step - loss: 0.2762 - acc: 0.9700
Epoch 257/500
100/100 [==============================] - 0s 66us/step - loss: 0.2764 - acc: 0.9600
Epoch 258/500
100/100 [==============================] - 0s 71us/step - loss: 0.2761 - acc: 0.9600
Epoch 259/500
100/100 [=

100/100 [==============================] - 0s 61us/step - loss: 0.2270 - acc: 0.9700
Epoch 332/500
100/100 [==============================] - 0s 61us/step - loss: 0.2275 - acc: 0.9700
Epoch 333/500
100/100 [==============================] - 0s 54us/step - loss: 0.2273 - acc: 0.9700
Epoch 334/500
100/100 [==============================] - 0s 62us/step - loss: 0.2265 - acc: 0.9700
Epoch 335/500
100/100 [==============================] - 0s 67us/step - loss: 0.2245 - acc: 0.9700
Epoch 336/500
100/100 [==============================] - 0s 64us/step - loss: 0.2235 - acc: 0.9700
Epoch 337/500
100/100 [==============================] - 0s 73us/step - loss: 0.2229 - acc: 0.9700
Epoch 338/500
100/100 [==============================] - 0s 70us/step - loss: 0.2228 - acc: 0.9600
Epoch 339/500
100/100 [==============================] - 0s 65us/step - loss: 0.2228 - acc: 0.9600
Epoch 340/500
100/100 [==============================] - 0s 64us/step - loss: 0.2231 - acc: 0.9600
Epoch 341/500
100/100 [=

100/100 [==============================] - 0s 57us/step - loss: 0.1907 - acc: 0.9800
Epoch 414/500
100/100 [==============================] - 0s 72us/step - loss: 0.1895 - acc: 0.9800
Epoch 415/500
100/100 [==============================] - 0s 54us/step - loss: 0.1888 - acc: 0.9700
Epoch 416/500
100/100 [==============================] - 0s 52us/step - loss: 0.1879 - acc: 0.9700
Epoch 417/500
100/100 [==============================] - 0s 66us/step - loss: 0.1876 - acc: 0.9700
Epoch 418/500
100/100 [==============================] - 0s 55us/step - loss: 0.1872 - acc: 0.9700
Epoch 419/500
100/100 [==============================] - 0s 50us/step - loss: 0.1873 - acc: 0.9700
Epoch 420/500
100/100 [==============================] - 0s 64us/step - loss: 0.1869 - acc: 0.9700
Epoch 421/500
100/100 [==============================] - 0s 51us/step - loss: 0.1861 - acc: 0.9700
Epoch 422/500
100/100 [==============================] - 0s 58us/step - loss: 0.1857 - acc: 0.9700
Epoch 423/500
100/100 [=

100/100 [==============================] - 0s 64us/step - loss: 0.1625 - acc: 0.9800
Epoch 496/500
100/100 [==============================] - 0s 60us/step - loss: 0.1623 - acc: 0.9800
Epoch 497/500
100/100 [==============================] - 0s 65us/step - loss: 0.1632 - acc: 0.9800
Epoch 498/500
100/100 [==============================] - 0s 64us/step - loss: 0.1632 - acc: 0.9800
Epoch 499/500
100/100 [==============================] - 0s 56us/step - loss: 0.1624 - acc: 0.9800
Epoch 500/500
100/100 [==============================] - 0s 56us/step - loss: 0.1610 - acc: 0.9800


In [48]:
loss, accuracy = model.evaluate(X_test, y_test)
loss, accuracy

50/50 [==============================] - 0s 1ms/step


(0.13147920221090317, 1.0)