# İşe Alım Robotu 
için K Nearest Neighbors Algoritmasını sıfırdan yazmanızı bekliyoruz. Aşağıdaki veriyi 

kullanabilirsiniz.

------------------------------

```
import numpy as np
import pandas as pd

import requests
import io


url = "https://raw.githubusercontent.com/uzay00/KaVe-Egitim/master/ARGE/Sorular/1-İseAlımRobotu/data.csv"
s = requests.get(url).content

data = pd.read_csv(io.StringIO(s.decode('utf-8')))
data
```

In [1]:
import numpy as np
import pandas as pd

import requests
import io


url = "https://raw.githubusercontent.com/uzay00/KaVe-Egitim/master/ARGE/Sorular/1-İseAlımRobotu/data.csv"
s = requests.get(url).content

data = pd.read_csv(io.StringIO(s.decode('utf-8')))
data

age  algorithm       gpa    social  y
0    3.576113   3.728920  0.930603  4.438372  1
1    1.829891   4.393183  3.137649  4.831307  1
2    3.981593   4.050717  3.886304  4.865860  1
3    1.734623   4.605488  2.605315  3.663224  1
4    2.759050   4.288383  1.894925  3.238931  1
..        ...        ...       ...       ... ..
995  0.756427   0.931875  2.769794  0.218749  0
996  3.344518   1.182757  2.696908  0.735196  0
997  1.812786   1.081876  2.940970  1.076683  0
998  2.316372   2.211849  4.594402  0.614308  0
999  1.845348   1.809162  3.783898  0.629247  0

[1000 rows x 5 columns]

In [4]:
X = data.values[:, :-1]
y = data.values[:, -1]

In [6]:
X.shape, y.shape

((1000, 4), (1000,))

In [7]:
a = np.array([3,4,1,3])
a

array([3, 4, 1, 3])

In [8]:
D = X - a

In [9]:
D.shape

(1000, 4)

In [10]:
D2 = D**2
D2.shape

(1000, 4)

In [12]:
M = D2.sum(axis = 1)
M.shape

(1000,)

In [13]:
S = M.argsort()
S.shape

(1000,)

In [19]:
k = 5
S[0:k]

array([ 4, 88, 59, 16, 29])

In [23]:
y[S[0:k]].mean() > 0.5

True

In [72]:
X = data.values[:, :-1]
y = data.values[:, -1]

def KNN(X, y, a, k):
    D = X - a
    D2 = D**2
    M = D2.sum(axis = 1)
    S = M.argsort()
    return y[S[0:k]].mean() > 0.5

In [73]:
KNN(X, y, a, k = 5)

True

In [74]:
KNN(X, y, a = np.array([0,0,0,0]), k = 5)

False

In [75]:
KNN(X, y, a = np.array([5,5,5,5]), k = 5)

True

In [76]:
KNN(X, y, a = np.array([0,5,0,5]), k = 5)

True

In [77]:
KNN(X, y, a = np.array([5,0,5,0]), k = 5)

False

In [78]:
A = np.array([[0,0,0,0],
              [5,5,5,5],
              [0,5,0,5],
              [5,0,5,0],
              [5,0,5,5],
              [5,5,5,5],
              ])

In [79]:
[KNN(X, y, a = A[i], k = 5) for i in range(len(A))]

[False, True, True, False, False, True]

# Thinking in Matrix

In [80]:
X3D = X.reshape(1, *X.shape)
X3D.shape

(1, 1000, 4)

In [81]:
X.shape

(1000, 4)

In [82]:
X

array([[3.5761132 , 3.72892034, 0.93060321, 4.43837203],
       [1.82989065, 4.39318298, 3.13764934, 4.83130749],
       [3.98159303, 4.05071661, 3.88630403, 4.86585961],
       ...,
       [1.81278649, 1.08187599, 2.94096983, 1.07668257],
       [2.31637186, 2.21184896, 4.59440187, 0.61430823],
       [1.8453481 , 1.80916171, 3.78389764, 0.62924677]])

In [83]:
X3D

array([[[3.5761132 , 3.72892034, 0.93060321, 4.43837203],
        [1.82989065, 4.39318298, 3.13764934, 4.83130749],
        [3.98159303, 4.05071661, 3.88630403, 4.86585961],
        ...,
        [1.81278649, 1.08187599, 2.94096983, 1.07668257],
        [2.31637186, 2.21184896, 4.59440187, 0.61430823],
        [1.8453481 , 1.80916171, 3.78389764, 0.62924677]]])

In [84]:
A.shape

(6, 4)

In [85]:
A3D = A.reshape(A.shape[0], 1, A.shape[1])
A3D.shape

(6, 1, 4)

In [86]:
A

array([[0, 0, 0, 0],
       [5, 5, 5, 5],
       [0, 5, 0, 5],
       [5, 0, 5, 0],
       [5, 0, 5, 5],
       [5, 5, 5, 5]])

In [87]:
A3D

array([[[0, 0, 0, 0]],

       [[5, 5, 5, 5]],

       [[0, 5, 0, 5]],

       [[5, 0, 5, 0]],

       [[5, 0, 5, 5]],

       [[5, 5, 5, 5]]])

In [88]:
D3D = X3D - A3D
D3D.shape

(6, 1000, 4)

In [89]:
KNN(X3D, y, A3D, k = 5)

True

In [90]:
D = X3D - A3D
D2 = D**2
M = D2.sum(axis = 2)
S = M.argsort()

In [91]:
S.shape

(6, 1000)

In [94]:
S[:, 0:k]

array([[759, 205, 712, 517, 702],
       [ 62,   2,  81,  94,  11],
       [ 90,  17,  12,  39,  75],
       [825, 675, 590, 522, 156],
       [604, 576, 831, 882,  19],
       [ 62,   2,  81,  94,  11]])

In [96]:
y[S[:, 0:k]]

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [97]:
y[S[:, 0:k]].mean(axis = 1) > 0.5

array([False,  True,  True, False, False,  True])

In [98]:
def KNN3D(X, y, a, k):
    D = X - a
    D2 = D**2
    M = D2.sum(axis = -1)
    S = M.argsort()
    return y[S[:, 0:k]].mean(axis = 1) > 0.5

In [99]:
KNN3D(X3D, y, A3D, k)

array([False,  True,  True, False, False,  True])