## Math

For Math: http://saitcelebi.com/tut/output/part2.html

## Keras

https://keras.io/#getting-started-30-seconds-to-keras


## Keras Steps

https://machinelearningmastery.com/5-step-life-cycle-neural-network-models-keras/

 - Define Network.
 - Compile Network.
 - Fit Network.
 - Evaluate Network.
 - Make Predictions.

## Iris Dataset for MultiClass Classification

Example taken from: https://machinelearningmastery.com/multi-class-classification-tutorial-keras-deep-learning-library/

In [97]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from keras.metrics import categorical_accuracy

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn import datasets 


# fix random seed for reproducibility
seed = 7
numpy.random.seed(seed)

iris = datasets.load_iris()

In [98]:
X, y = iris.data, iris.target

In [99]:
X.shape, y.shape

((150, 4), (150,))

In [100]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [101]:
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(y)
dummy_y[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [102]:
dummy_y[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [103]:
# create model
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))
# Compile model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [104]:
X_train, X_test, y_train, y_test = train_test_split(X, dummy_y, test_size=0.33, random_state=42)

In [105]:
# x_train and y_train are Numpy arrays --just like in the Scikit-Learn API.
model.fit(X_train, y_train, epochs=10, batch_size=16)

Epoch 1/10
100/100 [==============================] - 0s 4ms/step - loss: 1.2842 - acc: 0.3100
Epoch 2/10
100/100 [==============================] - 0s 103us/step - loss: 1.2510 - acc: 0.3100
Epoch 3/10
100/100 [==============================] - 0s 101us/step - loss: 1.2180 - acc: 0.3100
Epoch 4/10
100/100 [==============================] - 0s 94us/step - loss: 1.1866 - acc: 0.3300
Epoch 5/10
100/100 [==============================] - 0s 95us/step - loss: 1.1578 - acc: 0.3600
Epoch 6/10
100/100 [==============================] - 0s 103us/step - loss: 1.1264 - acc: 0.4800
Epoch 7/10
100/100 [==============================] - 0s 87us/step - loss: 1.0971 - acc: 0.6200
Epoch 8/10
100/100 [==============================] - 0s 101us/step - loss: 1.0713 - acc: 0.6400
Epoch 9/10
100/100 [==============================] - 0s 91us/step - loss: 1.0529 - acc: 0.6400
Epoch 10/10
100/100 [==============================] - 0s 96us/step - loss: 1.0389 - acc: 0.6200


In [106]:
loss, accuracy = model.evaluate(X_test, y_test)
loss, accuracy

50/50 [==============================] - 0s 3ms/step


(1.0149609851837158, 0.6600000071525574)

In [107]:
predictions = model.predict(X_test)
predictions

array([[0.281423  , 0.2403107 , 0.47826633],
       [0.36880517, 0.2920784 , 0.3391164 ],
       [0.18694662, 0.15879409, 0.6542593 ],
       [0.28994837, 0.24767037, 0.4623812 ],
       [0.24960506, 0.21753465, 0.5328603 ],
       [0.3518741 , 0.29752284, 0.350603  ],
       [0.30828804, 0.26952097, 0.42219093],
       [0.2585082 , 0.2195341 , 0.5219577 ],
       [0.22567025, 0.20913951, 0.5651902 ],
       [0.28522474, 0.25257057, 0.46220478],
       [0.28762922, 0.23744754, 0.47492328],
       [0.347865  , 0.3019945 , 0.3501405 ],
       [0.3554201 , 0.29661706, 0.3479628 ],
       [0.3513338 , 0.30036315, 0.34830305],
       [0.38132346, 0.29612342, 0.32255313],
       [0.30946907, 0.25374207, 0.43678883],
       [0.2686124 , 0.22063366, 0.5107539 ],
       [0.27852142, 0.25004348, 0.4714351 ],
       [0.2968921 , 0.25312126, 0.44998667],
       [0.25635424, 0.21637298, 0.5272727 ],
       [0.3632358 , 0.30070186, 0.33606237],
       [0.29046178, 0.24329454, 0.46624362],
       [0.

In [108]:
pred = np.argmax(predictions, axis = 1)
pred

array([2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 0, 0, 2, 2, 2, 2, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 2, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 2, 2, 2, 0,
       0, 2, 2, 2, 2, 2])

In [109]:
y_true =np.argmax(y_test, axis = 1)
y_true

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [110]:
np.mean(pred == y_true)

0.66

In [21]:
# define baseline model
def baseline_model():
    # create model
    model = Sequential()
    model.add(Dense(8, input_dim=4, activation='relu'))
    model.add(Dense(3, activation='softmax'))
    # Compile model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [22]:
estimator = KerasClassifier(build_fn=baseline_model, epochs=200, batch_size=5, verbose=0)

In [26]:
kfold = KFold(n_splits=10, shuffle=True, random_state=seed)

In [27]:
results = cross_val_score(estimator, X, dummy_y, cv=kfold)
print("Baseline: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

Instructions for updating:
keep_dims is deprecated, use keepdims instead
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Baseline: 97.33% (4.42%)
